version: '3'
services:
#  mongo:
#    image: mongo:latest
#    volumes:
#    - ./db/prod:/data/db
  server:
    build: ./server/
    ports:
     - "80:80"
#    environment:
#     - MONGODB_URI=mongodb://mongo:27017/privateToken
    env_file:
      - ./server/.env
#    links:
#     - mongo
#    depends_on:
#     - mongo
