version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
    - ./db/prod:/data/db
  server:
    build: ./server/
    ports:
     - "80:80"
    env_file: server/env.env
    volumes:
      - ./server/logs:/root/.npm/
    links:
     - mongo
    depends_on:
     - mongo