version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - mongo
      - server
    links:
      - mongo
      - server
    ports:
      - "80:80"
  mongo:
    image: mongo:latest
    volumes:
    - ./db/prod:/data/db
    ports:
    - "27017:27017"
  server:
    build:
      context: .
      dockerfile: server-prod.dockerfile
    working_dir: /var/www
    ports:
     - "3333:3333"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/explorer
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - ./server:/var/www
     - /var/www/node_modules