swagger: '2.0'
info:
    title: User API
    description: Happy to code User API
    version: '1.0.0'
schemes:
    - http
    - https
basePath: /
produces:
    - application/json
#securityDefinitions:
#  ApiKeyAuth:
#    type: apiKey
#    name: Authorization
#    in: header
paths:
    /membership/register:
        post:
            summary: Register a membership
            description: Register a membership
            parameters:
                - name: email
                  in: formData
                  description: Email of member
                  required: true
                  type: string
                - name: walletAddress
                  in: formData
                  description: Wallet address of member
                  required: true
                  type: string

            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Membership
    /membership/checkMember:
        get:
            summary: Check an wallet address is membership or not
            description: Check an wallet address is membership or not
            parameters:
                - name: walletAddress
                  in: query
                  description: Wallet address of member
                  required: true
                  type: string
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Membership
    /membership/getBalance:
        get:
            summary: Get balance of member
            description: Get balance of member
            parameters:
                - name: walletAddress
                  in: query
                  description: Wallet address of member
                  required: true
                  type: string
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Membership

    /membership/withdrawal:
        post:
            summary: withdrawal token from binkabi contract
            description: withdrawal token from binkabi contract
            parameters:
                - name: walletAddress
                  in: formData
                  description: Wallet address of member
                  required: true
                  type: string
                - name: amount
                  in: formData
                  description: Amount token withdrawal
                  required: true
                  type: number
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Membership

    /getAllContract:
        get:
            summary: list all contract address
            description: list all contract address
            responses:
                200:
                    description: OK
            tags:
                - Config

    /escrow/createOrder:
        post:
            summary: create an order before escrow
            description: create an order before escrow
            parameters:
                - name: buyer
                  in: formData
                  description: Wallet address of buyer
                  required: true
                  type: string
                - name: seller
                  in: formData
                  description: Wallet address of buyer
                  required: true
                  type: string
                - name: amountBuyer
                  in: formData
                  description: Amount BKB lock up of buyer
                  required: true
                  type: number
                - name: amountSeller
                  in: formData
                  description: Amount BKB lock up of seller
                  required: true
                  type: number
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Escrow

    /escrow/orderState/{orderId}:
        get:
            summary: create an order before escrow
            description: create an order before escrow
            parameters:
                - name: orderId
                  in: path
                  description: orderId
                  required: true
                  type: number
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Escrow

    /escrow/cancelOrder/{orderId}:
        post:
            summary: cancel order
            description: cancel order
            parameters:
                - name: orderId
                  in: path
                  description: orderId
                  required: true
                  type: number
                - name: fromMember
                  in: formData
                  description: Wallet address of member (buyer/seller)
                  required: true
                  type: string
                - name: refundBuyer
                  in: formData
                  description: Amount BKB refund to buyer
                  required: true
                  type: number
                - name: refundSeller
                  in: formData
                  description: Amount BKB refund to seller
                  required: true
                  type: number
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Escrow

    /escrow/refundingOrder/{orderId}:
        post:
            summary: refunding order
            description: When buyer said that product is not same description and want refund
            parameters:
                - name: orderId
                  in: path
                  description: orderId
                  required: true
                  type: number
                - name: fromMember
                  in: formData
                  description: Wallet address of member (buyer/seller)
                  required: true
                  type: string
                - name: hash
                  in: formData
                  description: hash of document
                  required: true
                  type: string
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Escrow

    /escrow/confirmRefunded/{orderId}:
        post:
            summary: refunded order
            description: Seller confirm receive his product
            parameters:
                - name: orderId
                  in: path
                  description: orderId
                  required: true
                  type: number
                - name: fromMember
                  in: formData
                  description: Wallet address of member (buyer/seller)
                  required: true
                  type: string
                - name: refundBuyer
                  in: formData
                  description: hash of document
                  required: true
                  type: number
                - name: refundSeller
                  in: formData
                  description: hash of document
                  required: true
                  type: number
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Escrow

    /escrow/deliverOrder/{orderId}:
        post:
            summary: deliver order
            description: When seller confirm send product
            parameters:
                - name: orderId
                  in: path
                  description: orderId
                  required: true
                  type: number
                - name: fromMember
                  in: formData
                  description: Wallet address of member (buyer/seller)
                  required: true
                  type: string
                - name: hash
                  in: formData
                  description: hash of document
                  required: true
                  type: string
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Escrow

    /escrow/completedOrder/{orderId}:
        post:
            summary: completed order
            description: When buyer confirm receive product
            parameters:
                - name: orderId
                  in: path
                  description: orderId
                  required: true
                  type: number
                - name: fromMember
                  in: formData
                  description: Wallet address of member (buyer/seller)
                  required: true
                  type: string
                - name: hash
                  in: formData
                  description: hash of document
                  required: true
                  type: string
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Escrow


    /escrow/uploadDocument/{orderId}:
        post:
            summary: upload Document
            description: When buyer/seller need upload more document
            parameters:
                - name: orderId
                  in: path
                  description: orderId
                  required: true
                  type: number
                - name: fromMember
                  in: formData
                  description: Wallet address of member (buyer/seller)
                  required: true
                  type: string
                - name: hash
                  in: formData
                  description: hash of document
                  required: true
                  type: string
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Escrow

    /vote/voting/{orderId}:
        post:
            summary: a member voting other member
            description: a member voting other member
            parameters:
                - name: fromMember
                  in: formData
                  description: member voting
                  required: true
                  type: string
                - name: toMember
                  in: formData
                  description: member
                  required: true
                  type: string
                - name: orderId
                  in: path
                  description: orderId
                  required: true
                  type: number
                - name: score
                  in: formData
                  description: score
                  required: true
                  type: number
                - name: comment
                  in: formData
                  description: comment
                  required: true
                  type: string
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Vote

    /vote/getScore:
        get:
            summary: get score of a member
            description: get score of a member
            parameters:
                - name: member
                  in: query
                  description: member
                  required: true
                  type: string
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Vote


    /vote/getComent:
        get:
            summary: get comment
            description: get comment
            parameters:
                - name: member
                  in: query
                  description: member
                  required: true
                  type: string
                - name: indexComment
                  in: query
                  description: indexComment
                  required: true
                  type: number
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Vote

    /vote/checkIsVoted:
        get:
            summary: get comment
            description: get comment
            parameters:
                - name: member
                  in: query
                  description: member
                  required: true
                  type: string
                - name: orderId
                  in: query
                  description: indexComment
                  required: true
                  type: number
            responses:
                200:
                    description: OK
                400:
                    description: Bad Request
            tags:
                - Vote
